### ISSUE TITLE
Check the `Content-Length` of the response, and then retry the download if it doesn't match

### ISSUE THREAD

**Issue by vjpr** [pnpm/package-store#2]
More details: 
- https://github.com/pnpm/pnpm/issues/872
- https://github.com/npm/registry/issues/202

Maybe it should be added to `npm-registry-client` in the future, but the retry logic should be managed by us.

**Comment by zkochan** [comment]
`npm-registry-client` already retries in a lot of cases, see the different retry configs: https://github.com/npm/npm-registry-client#configuration
